prev/next link and subscribe bug fixed
LikaloLLC/BlogVi pull request #8
Opened 2021-05-07 19:03 UTC by Zarif99

2021-05-07 19:41 UTC, 1mace1 requested changes

2021-05-07 19:41 UTC, 1mace1 commented on src/blog_vi/templates/base_blog.html
>    <h2 class="font-bold break-normal text-2xl md:text-4xl">Subscribe to Ghostwind CSS</h2>
You should replace `Subscribe to Ghostwind CSS` to `{{subscribe.title}}`

2021-05-07 19:41 UTC, 1mace1 commented on src/blog_vi/templates/base_blog.html
> +</div>
Remove this

2021-05-09 19:22 UTC, 1mace1 approved these changes

2021-05-09 21:59 UTC, PhilippeTrounev approved these changes

2021-05-09 21:59 UTC, merged